version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
# 検証環境用
[stg.deploy.parameters]
stack_name = "web-rtc"
s3_bucket = "aws-isystk-com-sam"
s3_prefix = "web-rtc"
region = "ap-northeast-1"
profile = "web-rtc"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides="TableName=web_rtc"
# 本番環境用
[prd.deploy.parameters]
stack_name = "xxxxxx"
s3_bucket = "xxxxxx"
s3_prefix = "xxxxxxx"
region = "ap-northeast-1"
profile = "xxxxxxx"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides="TableName=web_rtc"
