version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "web-rtc"
s3_bucket = "aws-isystk-com-sam"
s3_prefix = "web-rtc"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"