AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-lambda-posts

  Sample SAM Template for aws-lambda-posts
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

  # Lambda & APIGateway を作成
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: lambda.handler
      Runtime: nodejs16.x
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: ""
      Layers:
        - "arn:aws:lambda:ap-northeast-1:004796740041:layer:SharedLayer:5"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  # DynamoDB のテーブルを作成
  AppTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: web-rtc
      AttributeDefinitions: 
        - AttributeName: connection_id
          AttributeType: S
      KeySchema: 
        - AttributeName: connection_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AppApi:
    Description: "API Gateway endpoint URL for Prod stage for App function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/posts/"
  AppFunction:
    Description: "App Lambda Function ARN"
    Value: !GetAtt AppFunction.Arn